[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
SubspaceClustering = "bea3bcab-479e-4b6c-b047-c6cd33cd022c"

[sources]
SubspaceClustering = {path = ".."}

[compat]
CairoMakie = "0.13"
Documenter = "1.10"
LiveServer = "1.5"
julia = "1.11"
